name: CI
on: [push, pull_request]
jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      
      - run: git submodule update --init --depth=1 modules/translate
      - run: git submodule update --init --depth=1 modules/utilities
      - run: git submodule update --init --depth=1 modules/zotero-schema
      - run: git submodule update --init --depth=1 modules/translators
      
      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: 16
      
      - run: npm ci
      - run: npm test